<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.acme</groupId>
    <artifactId>acme-parent</artifactId>
    <version>1.2.3</version>
  </parent>
  <groupId>com.acme</groupId>
  <artifactId>child-module</artifactId>

  <dependencies>
    <dependency>
      <groupId>com.acme</groupId>
      <artifactId>shared</artifactId>
      <version>${project.version}</version>
    </dependency>
  </dependencies>
</project>
