name: Test

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  rust-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools-preview

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Install cargo-audit
        uses: taiki-e/install-action@cargo-audit

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2

      - name: CI gate
        run: ./harness ci
